### ISSUE TITLE
Spelling error on front page

### ISSUE THREAD

**Issue by iloveitaly** [griptape-ai/griptape-docs#135]
`Similarities` on the front page:

```
Explain the similaritiies about these movies:
```

**Comment by collindutter** [comment]
@shhlife this is in the Workflow example on [griptape.ai](https://griptape.ai/). Can you please update?

**Comment by shhlife** [comment]
yep, I'll get right on it!

**Comment by shhlife** [comment]
Fixed! Thank you :)

![image](https://github.com/griptape-ai/griptape-docs/assets/5397345/e21617e6-cc0d-4c13-ba37-d6d7a0f21d1b)
