### ISSUE TITLE
Missing docs on Ramps?

### ISSUE THREAD

**Issue by klauern** [griptape-ai/griptape-docs#26]
I see it mentioned in the https://github.com/griptape-ai/griptape#quick-start, but not sure what it is.  I haven't built anything with this, but I was perusing the docs to understand it and saw the gap

**Comment by vasinov** [comment]
@klauern, indeed! We are working on updating our docs to describe new functionality. Will ping you here once it's out.

**Comment by vasinov** [comment]
@klauern, we finally added some docs about ramps: https://docs.griptape.ai/en/latest/griptape-framework/ramps/
