### ISSUE TITLE
Links to "Learn more about..." are broken on main page

### ISSUE THREAD

**Issue by shhlife** [griptape-ai/griptape-docs#3]
Hello! 

Just wanted to let you know that I noticed the "learn more" links are broken on the main docs page.

If you go to https://griptape.readthedocs.io/en/latest/ and click on the "Learn more about Griptape" or "Learn more about Skatepark" the links are missing "en/language" in the url.

They point to: https://griptape.readthedocs.io/griptape and https://griptape.readthedocs.io/skatepark, but should point to https://griptape.readthedocs.io/en/latest/griptape/ and https://griptape.readthedocs.io/en/latest/skatepark/ respectively.

Cheers!
-Jason

**Comment by vasinov** [comment]
Thanks for reporting it! Should be fixed now.
