### ISSUE TITLE
Decorator description bugs in griptape-tools RestApiClient

### ISSUE THREAD

**Issue by ysammy** [griptape-ai/griptape-docs#31]
I found a few decorator description bugs while browsing https://github.com/griptape-ai/griptape-tools/blob/main/griptape/tools/rest_api_client/tool.py.

https://github.com/griptape-ai/griptape-tools/blob/main/griptape/tools/rest_api_client/tool.py#L71 : s/post/patch/
https://github.com/griptape-ai/griptape-tools/blob/main/griptape/tools/rest_api_client/tool.py#L110 : s/patch/post/
https://github.com/griptape-ai/griptape-tools/blob/main/griptape/tools/rest_api_client/tool.py#L189 : s/get/delete/

Happy to open a PR.

**Comment by kyleroche** [comment]
PR would be awesome. Then I can claim you're an official contributor :)

**Comment by collindutter** [comment]
@vasinov I believe this can be closed.
