### ISSUE TITLE
Clarify that we should have python-decouple installed in the QuickStart documentation

### ISSUE THREAD

**Issue by shhlife** [griptape-ai/griptape-docs#5]
In the quickstart documentation the instructions say to install Skatepark, Griptape Tools, and Decouple, but then the code only shows:

`pip install skatepark-lib griptape-tools`

In Visual Studio Code I was getting a Pylance error:
![image](https://user-images.githubusercontent.com/5397345/232339765-f39da465-3042-479b-a883-8bd5b10a6cb3.png)

so thought maybe I had to install decouple.

I did a `pip install decouple` which completely broke things. :)

I then had to `pip uninstall decouple`, and make sure python-decouple was up to date.

Probably best to call out python-decouple at the top of the QuickStart docs.

cheers,
Jason

**Comment by vasinov** [comment]
I [added](https://github.com/griptape-ai/griptape-core/blob/169a009df6bcbb3921b85ba2de6829d9a8ae6b13/pyproject.toml#L26) an explicit dependency on `python-decouple` to `griptape-core` a couple of days ago, so it should be always installed transitively.

I wonder if the reason VS Code highlights it is because it's pointing at the wrong Python environment.

**Comment by shhlife** [comment]
It appears to be the right Python environment.. I tried a few things, and it seems like since the code is running correctly it's just a false positive. I resolved the error by changing Pylance settings to turn off Type Checking mode.

**Comment by shhlife** [comment]
The new documentation is much clearer, thank you! It does a great job of stepping through the process from a new-user perspective - Nicely done!

I did get a bug after running the code though:
```[04/18/23 12:15:42] ERROR    Step c66124ce980d4059a5dda8b9348a2742
                             Invalid JSON: {'description': 'Number of decimals to round the random number to', 'type':    
                             'integer', '$id': 'ToolInputSchema', '$schema': 'http://json-schema.org/draft-07/schema#',   
                             'default': 5} is not of type 'integer'

                             Failed validating 'type' in schema:
                                 {'$id': 'ToolInputSchema',
                                  '$schema': 'http://json-schema.org/draft-07/schema#',
                                  'description': 'Number of decimals to round the random number to',
                                  'type': 'integer'}

                             On instance:
                                 {'$id': 'ToolInputSchema',
                                  '$schema': 'http://json-schema.org/draft-07/schema#',
                                  'default': 5,
                                  'description': 'Number of decimals to round the random number to',
                                  'type': 'integer'}
```

-Jason
