### ISSUE TITLE
Add a bit more detail to the Custom Tools documentation

### ISSUE THREAD

**Issue by shhlife** [griptape-ai/griptape-docs#6]
The Custom Tools documentation could use a little more step-by-step instruction.

For this custom tool, is it recommended to create a tools folder in the current project, or add their custom tools to the griptape/tools folder?

Let's say they've got a project called learning_griptape, and they want to use the random_number_generator in a file called random_test.py.

If they create a tools directory, what is the recommended structure to get this to work correctly? I'm assuming something like:

```
learning_griptape/
  random_test.py
  tools/
    random_number_generator/
      __init__.py
      manifest.yaml
      requirements.txt
      tool.py
```

do you also need an __init__.py in the tools/ directory?

if that's the case, and the user wants to use the LocalExecutor() command specified in the docs, could you specify exactly the import calls in the random_test.py, and how you'd call RandomNumberGenerator?

I tried a number of things & couldn't get it working. I'm sure it's a simple thing, but since this is getting started documentation, it'd be good to include all of the steps.

thanks!
-Jason

**Comment by vasinov** [comment]
Just pushed an update with a cleaned up example: https://griptape.readthedocs.io/en/latest/griptape/tools/custom_tools/

Let me know if you think it can still be improved.

**Comment by shhlife** [comment]
The new documentation is much clearer, thank you! It does a great job of stepping through the process from a new-user perspective - Nicely done!

I did get a bug after running the code though:
```[04/18/23 12:15:42] ERROR    Step c66124ce980d4059a5dda8b9348a2742
                             Invalid JSON: {'description': 'Number of decimals to round the random number to', 'type':    
                             'integer', '$id': 'ToolInputSchema', '$schema': 'http://json-schema.org/draft-07/schema#',   
                             'default': 5} is not of type 'integer'

                             Failed validating 'type' in schema:
                                 {'$id': 'ToolInputSchema',
                                  '$schema': 'http://json-schema.org/draft-07/schema#',
                                  'description': 'Number of decimals to round the random number to',
                                  'type': 'integer'}

                             On instance:
                                 {'$id': 'ToolInputSchema',
                                  '$schema': 'http://json-schema.org/draft-07/schema#',
                                  'default': 5,
                                  'description': 'Number of decimals to round the random number to',
                                  'type': 'integer'}
```

-Jason

**Comment by vasinov** [comment]
That's a known issue with GPT-3.5 not picking up the right schema if there is only one tool...there is a fix in the main branch but we haven't pushed it as a new package version yet. For now, just add any other tool to the step; strangely enough it gives the LLM enough context to generalize the schema correctly.

**Comment by shhlife** [comment]
I went through it with the latest build and it worked perfectly! Great job! :)
